name: Test 

on: 
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tests
        run: echo "Tests!"